pipeline {

    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKERHUB_REPOSITORY_NAME = 'fq1444/tema-final-01'
    }
    stages {

        stage('Get artifact from JFrog server') {
            steps {
                rtDownload (
                    serverId: "temafinal1",
                    spec: """{
                        "files": [
                            {
                                "pattern": "temafinal1/helloworld.war",
                                "target": "job1/build/libs/helloworld.war"
                            }
                        ]
                    }"""
                )
            }
        }

        stage('Packer build') {
            steps {
                bat 'packer build  -var "dockerhub_repository_name=$fq1444/tema-final-01" -var "dockerhub_username=$fq1444" -var "dockerhub_user_password=$741236985fq" "job2/packerConfig.json"'
            }
        }
    }
}