pipeline {

    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKERHUB_REPOSITORY_NAME = 'fq1444/tema-final-01'
    }
    stages {

        stage('Get artifact from JFrog server') {
            steps {
                rtDownload (
                    serverId: "temafinal1",
                    spec: """{
                        "files": [
                            {
                                "pattern": "temafinal1/helloworld.war",
                                "target": "job1/build/libs/helloworld.war"
                            }
                        ]
                    }"""
                )
            }
        }

        stage('Packer build') {
            steps {
                bat 'packer init "C:/ProgramData/Jenkins/.jenkins/workspace/job2/job2/docker-with-jar.pkr.hcl"'
                bat 'packer build  "C:/ProgramData/Jenkins/.jenkins/workspace/job2/job2/docker-with-jar.pkr.hcl"'
            }
        }
    }
}