pipeline {

    agent any

    stages {

        stage('Clone repository') {
            steps {
                git branch: 'master', url: "https://github.com/felipe-quirino-ilegra/temafinal1.git"
            }
        }

        stage('Test application') {
            steps {
                bat './gradlew test'
            }
        }

        stage('Build application') {
            steps {
                bat './gradlew build'
            }
        }

        stage('Publish artifactory') {
            steps {
                rtUpload (
                    serverId: "temafinal1",
                    spec: """{
                                "files": [
                                    {
                                        "pattern": "build/libs/helloworld.war",
                                        "target": "temafinal1"
                                    }
                                ]
                    }"""
                )
            }
        }
    }
}